# ユーザ作成処理
POST http://localhost:5000/api/v1/posts
Content-Type: application/json

# body
{
    "title":"テスト用投稿",
    "description":"テスト用投稿説明",
    "userId":"627e60ca2b32e7c32c08c42e"
}


# 以下正のレスポンス
# HTTP/1.1 201 Created
# X-Powered-By: Express
# Content-Type: application/json; charset=utf-8
# Content-Length: 251
# ETag: W/"fb-e2RG+BC5YKhIiqQODRru3UbTIpU"
# Date: Fri, 13 May 2022 16:10:32 GMT
# Connection: close

# {
#   "title": "テスト用投稿",
#   "description": "テスト用投稿説明",
#   "likes": [],
#   "auther": "627e60ca2b32e7c32c08c42e",
#   "comments": [],
#   "_id": "627e82f8eb4c1558d59f2fa3",
#   "createdAt": "2022-05-13T16:10:32.201Z",
#   "updatedAt": "2022-05-13T16:10:32.201Z",
#   "__v": 0
# }



# 以下異常のレスポンス
# HTTP/1.1 400 Bad Request
# X-Powered-By: Express
# Content-Type: application/json; charset=utf-8
# Content-Length: 35
# ETag: W/"23-DbBOAtrFiaA/pDkW921qsV2RgH4"
# Date: Fri, 13 May 2022 16:10:59 GMT
# Connection: close

# {
#   "massege": "値が不十分です"
# }
