# ユーザ全取得処理
GET /api/v1/users HTTP/1.1
Host: localhost:5000



# 以下レスポンス
# HTTP/1.1 200 OK
# X-Powered-By: Express
# Content-Type: application/json; charset=utf-8
# Content-Length: 266
# ETag: W/"10a-WNvYbSxTbQTmulEKghRyXXURqns"
# Date: Fri, 13 May 2022 14:00:18 GMT
# Connection: close

# ペイロード
# [
#   {
#     "_id": "627e60ca2b32e7c32c08c42e",
#     "username": "TestUser",
#     "email": "test@test.com",
#     "password": "test",
#     "followers": [],
#     "followings": [],
#     "isAdmin": false,
#     "isLogin": false,
#     "isActive": false,
#     "createdAt": "2022-05-13T13:44:42.412Z",
#     "updatedAt": "2022-05-13T13:44:42.412Z",
#     "__v": 0
#   }
# ]
